/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Admin
 */
public class FrMain extends javax.swing.JFrame {

    /**
     * Creates new form FrMain
     */
    public FrMain() {
        initComponents();
        setTitle("Quản lý sinh viên");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnQLTK = new javax.swing.JButton();
        btnQLHoDanCu = new javax.swing.JButton();
        btnQuanLyNguoiDan = new javax.swing.JButton();
        btnXemPhanHoi = new javax.swing.JButton();
        btnGuiThongBao = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnQLTK.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/account_32.png"))); // NOI18N
        btnQLTK.setText("Quản lý tài khoản");
        btnQLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTKActionPerformed(evt);
            }
        });

        btnQLHoDanCu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLHoDanCu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_243_32.png"))); // NOI18N
        btnQLHoDanCu.setText("Quản lý hộ dân cư");
        btnQLHoDanCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHoDanCuActionPerformed(evt);
            }
        });

        btnQuanLyNguoiDan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQuanLyNguoiDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/users_icon-icons.com_57999.png"))); // NOI18N
        btnQuanLyNguoiDan.setText("Quản lý người dân");
        btnQuanLyNguoiDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNguoiDanActionPerformed(evt);
            }
        });

        btnXemPhanHoi.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnXemPhanHoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/noti_32.png"))); // NOI18N
        btnXemPhanHoi.setText("Xem phản hồi");
        btnXemPhanHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemPhanHoiActionPerformed(evt);
            }
        });

        btnGuiThongBao.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnGuiThongBao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_send_32.png"))); // NOI18N
        btnGuiThongBao.setText("Gửi thông báo");
        btnGuiThongBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiThongBaoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_icon-icons.com_73532.png"))); // NOI18N

        btnDangXuat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_icon_32.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanLyNguoiDan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuiThongBao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXemPhanHoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLHoDanCu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLTK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(122, 122, 122)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 1103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQLTK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btnQLHoDanCu)
                        .addGap(71, 71, 71)
                        .addComponent(btnQuanLyNguoiDan)
                        .addGap(78, 78, 78)
                        .addComponent(btnXemPhanHoi)
                        .addGap(76, 76, 76)
                        .addComponent(btnGuiThongBao)
                        .addGap(69, 69, 69)
                        .addComponent(btnDangXuat)))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 681, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTKActionPerformed
        // TODO add your handling code here:
        QuanLyTaiKhoan qltk = new QuanLyTaiKhoan();
        qltk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLTKActionPerformed

    private void btnQLHoDanCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHoDanCuActionPerformed
        // TODO add your handling code here:
        frHoDan hodan  = new frHoDan();
        hodan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLHoDanCuActionPerformed

    private void btnQuanLyNguoiDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNguoiDanActionPerformed
        // TODO add your handling code here:
        DSNGuoiDan dsngd = new DSNGuoiDan();
        dsngd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuanLyNguoiDanActionPerformed

    private void btnXemPhanHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemPhanHoiActionPerformed
        // TODO add your handling code here:
        XemPhanHoi xemPhanHoi = new XemPhanHoi();
        xemPhanHoi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnXemPhanHoiActionPerformed

    private void btnGuiThongBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiThongBaoActionPerformed
        // TODO add your handling code here:
        GuiThongBao guiThongBao = new GuiThongBao();
        guiThongBao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGuiThongBaoActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnGuiThongBao;
    private javax.swing.JButton btnQLHoDanCu;
    private javax.swing.JButton btnQLTK;
    private javax.swing.JButton btnQuanLyNguoiDan;
    private javax.swing.JButton btnXemPhanHoi;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
